# Site settings
title: Aimee Does Coding
header-img: img/home-bg.png
email: acarney29@gmail.com
copyright_name: aimeecarney
description: > # this means to ignore newlines until "baseurl:"
  Thoughts, Ramblings and My Journey to Becoming a Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  aimeecarney
learn_profile: aimeecarney
email_username: acarney29@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
